### ISSUE TITLE
[fix]: re-feed matches to a higher-level query if it uses another query on the same node as input

### ISSUE THREAD

**Issue by Kristina-Pianykh** [Kristina-Pianykh/flink-multinode#21]
Related to #20

**Comment by piankris** [comment]
Chaining query match streaming when one query is an input to another query on the same node requires emitting watermark upon creating complex events. I ain't touching it for now.

The (temporary) solution is to add a forwarding rule for such a node to send the matches of the one query to itself. This is a way faster fix (adding one line to config) and doesn't mess with watermarking in the flink system. For now, watermarks are emitted in one place only: in the source function upon receiving an event via tcp.

**Comment by Kristina-Pianykh** [comment]
Chaining query match streaming when one query is an input to another query on the same node [requires emitting watermark](https://stackoverflow.com/questions/64276898/flink-cep-cannot-get-correct-results-on-a-unioned-table) upon creating complex events. I ain't touching it for now.

The (temporary) solution is to add a forwarding rule for such a node to send the matches of the one query to itself. This is a way faster fix (adding one line to config) and doesn't mess with watermarking in the flink system. For now, watermarks are emitted in one place only: in the source function upon receiving an event via tcp.

**Comment by Kristina-Pianykh** [comment]
Resolved in #25 specifically in commits https://github.com/Kristina-Pianykh/flink-multinode/pull/25/commits/a11aa54fad6e9ab8de4bf554e6cfb8c9ae3a8251 and https://github.com/Kristina-Pianykh/flink-multinode/pull/25/commits/67aef91fea8217382118065b322f32bcf28cac23
